const imgLink = "https://cdn.sodiedoces.com.br/wp-content/uploads/2025/03/12164612/FATIA.png";

export const bolos = [
    { nome: "Bolo de Chocolate", img: imgLink, sabor: "Chocolate", preco: 45.90 },
    { nome: "Bolo de Baunilha", img: imgLink, sabor: "Baunilha", preco: 42.00 },
    { nome: "Bolo de Morango", img: imgLink, sabor: "Morango", preco: 48.50 },
    { nome: "Bolo de Coco", img: imgLink, sabor: "Coco", preco: 46.00 },
    { nome: "Bolo de Limão", img: imgLink, sabor: "Limão", preco: 44.00 },
    { nome: "Bolo de Cenoura", img: imgLink, sabor: "Cenoura", preco: 43.50 },
    { nome: "Bolo de Nozes", img: imgLink, sabor: "Nozes", preco: 55.00 },
    { nome: "Bolo de Maracujá", img: imgLink, sabor: "Maracujá", preco: 47.00 },
    { nome: "Bolo Red Velvet", img: imgLink, sabor: "Red Velvet", preco: 60.00 },
    { nome: "Bolo de Café", img: imgLink, sabor: "Café", preco: 49.00 },
    { nome: "Bolo de Abacaxi", img: imgLink, sabor: "Abacaxi", preco: 46.50 },
    { nome: "Bolo de Laranja", img: imgLink, sabor: "Laranja", preco: 44.50 },
    { nome: "Bolo de Amendoim", img: imgLink, sabor: "Amendoim", preco: 52.00 },
    { nome: "Bolo de Brigadeiro", img: imgLink, sabor: "Brigadeiro", preco: 50.00 },
    { nome: "Bolo de Leite Ninho", img: imgLink, sabor: "Leite Ninho", preco: 53.00 },
    { nome: "Bolo de Doce de Leite", img: imgLink, sabor: "Doce de Leite", preco: 51.00 },
    { nome: "Bolo de Uva", img: imgLink, sabor: "Uva", preco: 48.00 },
    { nome: "Bolo de Pêssego", img: imgLink, sabor: "Pêssego", preco: 47.50 },
    { nome: "Bolo de Maçã", img: imgLink, sabor: "Maçã", preco: 45.00 },
    { nome: "Bolo de Banana", img: imgLink, sabor: "Banana", preco: 44.00 },
    { nome: "Bolo de Castanha", img: imgLink, sabor: "Castanha", preco: 54.00 },
    { nome: "Bolo de Nutella", img: imgLink, sabor: "Nutella", preco: 62.00 },
    { nome: "Bolo de Paçoca", img: imgLink, sabor: "Paçoca", preco: 50.00 },
    { nome: "Bolo de Trufa", img: imgLink, sabor: "Trufa", preco: 58.00 },
    { nome: "Bolo de Mousse de Limão", img: imgLink, sabor: "Mousse de Limão", preco: 56.00 },
    { nome: "Bolo de Mousse de Maracujá", img: imgLink, sabor: "Mousse de Maracujá", preco: 56.00 },
    { nome: "Bolo de Mousse de Chocolate", img: imgLink, sabor: "Mousse de Chocolate", preco: 59.00 },
    { nome: "Bolo de Mousse de Morango", img: imgLink, sabor: "Mousse de Morango", preco: 59.00 },
    { nome: "Bolo de Mousse de Uva", img: imgLink, sabor: "Mousse de Uva", preco: 59.00 },
    { nome: "Bolo de Mousse de Coco", img: imgLink, sabor: "Mousse de Coco", preco: 59.00 },
    { nome: "Bolo de Mousse de Abacaxi", img: imgLink, sabor: "Mousse de Abacaxi", preco: 59.00 },
    { nome: "Bolo de Mousse de Frutas Vermelhas", img: imgLink, sabor: "Mousse de Frutas Vermelhas", preco: 59.00 },
    { nome: "Bolo de Mousse de Maracujá com Chocolate", img: imgLink, sabor: "Maracujá com Chocolate", preco: 61.00 },
    { nome: "Bolo de Mousse de Limão com Chocolate", img: imgLink, sabor: "Limão com Chocolate", preco: 61.00 },
    { nome: "Bolo de Mousse de Morango com Chocolate", img: imgLink, sabor: "Morango com Chocolate", preco: 61.00 },
    { nome: "Bolo de Mousse de Coco com Chocolate", img: imgLink, sabor: "Coco com Chocolate", preco: 61.00 },
    { nome: "Bolo de Mousse de Abacaxi com Chocolate", img: imgLink, sabor: "Abacaxi com Chocolate", preco: 61.00 },
    { nome: "Bolo de Mousse de Frutas Vermelhas com Chocolate", img: imgLink, sabor: "Frutas Vermelhas com Chocolate", preco: 61.00 },
    { nome: "Bolo de Brigadeiro Branco", img: imgLink, sabor: "Brigadeiro Branco", preco: 52.00 },
    { nome: "Bolo de Brigadeiro com Morango", img: imgLink, sabor: "Brigadeiro com Morango", preco: 54.00 },
    { nome: "Bolo de Brigadeiro com Uva", img: imgLink, sabor: "Brigadeiro com Uva", preco: 54.00 },
    { nome: "Bolo de Brigadeiro com Coco", img: imgLink, sabor: "Brigadeiro com Coco", preco: 54.00 },
    { nome: "Bolo de Brigadeiro com Abacaxi", img: imgLink, sabor: "Brigadeiro com Abacaxi", preco: 54.00 },
    { nome: "Bolo de Brigadeiro com Frutas Vermelhas", img: imgLink, sabor: "Brigadeiro com Frutas Vermelhas", preco: 54.00 },
    { nome: "Bolo de Brigadeiro com Limão", img: imgLink, sabor: "Brigadeiro com Limão", preco: 54.00 },
    { nome: "Bolo de Brigadeiro com Maracujá", img: imgLink, sabor: "Brigadeiro com Maracujá", preco: 54.00 },
    { nome: "Bolo de Brigadeiro com Castanha", img: imgLink, sabor: "Brigadeiro com Castanha", preco: 56.00 },
    { nome: "Bolo de Brigadeiro com Nozes", img: imgLink, sabor: "Brigadeiro com Nozes", preco: 56.00 },
    { nome: "Bolo de Brigadeiro com Amendoim", img: imgLink, sabor: "Brigadeiro com Amendoim", preco: 56.00 },
    { nome: "Bolo de Brigadeiro com Paçoca", img: imgLink, sabor: "Brigadeiro com Paçoca", preco: 56.00 },
    { nome: "Bolo de Brigadeiro com Nutella", img: imgLink, sabor: "Brigadeiro com Nutella", preco: 64.00 },
    { nome: "Bolo de Brigadeiro com Leite Ninho", img: imgLink, sabor: "Brigadeiro com Leite Ninho", preco: 58.00 },
    { nome: "Bolo de Brigadeiro com Doce de Leite", img: imgLink, sabor: "Brigadeiro com Doce de Leite", preco: 58.00 },
    { nome: "Bolo de Brigadeiro com Café", img: imgLink, sabor: "Brigadeiro com Café", preco: 58.00 },
    { nome: "Bolo de Brigadeiro com Red Velvet", img: imgLink, sabor: "Brigadeiro com Red Velvet", preco: 62.00 },
    // ...adicione mais bolos se quiser...
];